/*
 * Copyright (c) TIBCO Software Inc. 2005.
 * All Rights Reserved.
 */
package com.tibco.bw.sharedresource.tas.runtime;

import com.tibco.neo.localized.BundleMessage;
import com.tibco.neo.localized.MessageBundle;

/**
 * A message bundle for this package.

 * THIS FILE WAS AUTOMATICALLY GENERATED BY A CONVERSION TOOL.
 * IF YOU EDIT IT, YOU MAY LOSE YOUR CHANGES.
 */
public class RuntimeMessageBundle extends MessageBundle {

    // Following member is accessed by MessageBundle.initializeMessages, do not remove!
    static public final String BUNDLE_NAME = "com.tibco.bw.sharedresource.tas.runtime.Resources"; //$NON-NLS-1$

    static {
        MessageBundle.initializeMessages(RuntimeMessageBundle.class);
    }

    public static BundleMessage DEBUG_CREATE_SHAREDRESOURCE;
    public static BundleMessage DEBUG_UPDATE_SHAREDRESOURCE;
    public static BundleMessage DEBUG_DELETE_SHAREDRESOURCE;
    public static BundleMessage DEBUG_STOP_SHAREDRESOURCE;
    public static BundleMessage DEBUG_START_SHAREDRESOURCE;
    public static BundleMessage ERROR_CREATE_SHAREDRESOURCE_FAILED;

    public static BundleMessage ERROR_EMPTY_INPUT_SCHEMA;
    public static BundleMessage ERROR_EMPTY_OUTPUT_SCHEMA;

    public static BundleMessage MESSAGE_FORMAT1;
}
